### PR TITLE
Sync state in current tab

### LINKED ISSUE #28: State not syncing across components
**Describe the bug**
When you modify localStorage from another tab, the state updates correctly. However when you modify state from another component, an update is not triggered. This library lacks a pub/sub to make it possible.

**To Reproduce**
Click one button here. The other should update as well (but it doesn't):
https://codesandbox.io/s/xenodochial-herschel-xptrbl?file=/src/App.js

**Expected behavior**
The state syncs for the same component (works), across components (bug) and across tabs (works). Only across components is broken now, which is very odd.

**Screenshots**
image

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
I'd recommend a simple pub/sub system across keys and using the provided callbacks.

### PR DESCRIPTION
**Pull request by guoyunhe**
Sync localStorage state in current browser tab by manually fire storage events.

Fix #28

### CODE REVIEW

**Review by franciscop — APPROVED** [review]
Looks good! Probably works fine since [it is already listening to this event](https://github.com/nas5w/use-local-storage/blob/master/index.ts#L82), right? Awesome to see this change merged in 🥳

**Review by franciscop — CHANGES_REQUESTED** [review]
Actually a concern: won't this trigger two re-renders of the same hook? One update on the `setValue()`, and then dispatching this event will trigger another update on the hook listening for the event. Two solutions:
- We could probably at this point remove the whole local state and make it all based on the events.
- ~We could modify the setValue to trigger the event~ this would also result in two renders.

**Comment by guoyunhe** [comment]
@franciscop indeed, need to add some sort of comparison.

**Comment by guoyunhe** [comment]
@franciscop I have updated the PR. Introduced a ref called `rawValueRef` that store and compare raw localStorage values. So it won't update when the actual serialized content isn't change.

**Comment by franciscop** [comment]
Oh it was much easier, you could have done this:

```js
if (e.newValue === serializer(storedValue)) return;
}, [key, syncData, storedValue]);
```

**Comment by guoyunhe** [comment]
@franciscop I took performance into consideration. Using ref will reduce a lot of unnecessary serialization, which can be slow.

**Comment by franciscop** [comment]
True! Code looks good 👍 , let's see what @nas5w says :)

**Review by franciscop — APPROVED** [review]

File: index.ts [hunk 1]
```diff
@@ -50,19 +54,40 @@ function useLocalStorage<T>(
...
+        const oldValue = rawValueRef.current;
+        rawValueRef.current = newValue;
+        window.localStorage.setItem(key, newValue);
+        window.dispatchEvent(
+          new StorageEvent("storage", {
+            storageArea: window.localStorage,
+            url: window.location.href,
+            key,
+            newValue,
+            oldValue,
```
Comment (franciscop) [inline index.ts:70]: `oldValue` is not used anywhere?

Comment (guoyunhe) [reply index.ts:70]: @franciscop it is not used in useLocalStorage. But it exists in native StorageEvent. So it is better to have it, in case some other libraries need it.

**Comment by nas5w** [comment]
Will review this shortly! Thank you guys!!

**Comment by nas5w** [comment]
This looks awesome! I just want to take a step back and discuss this approach to make sure it won't have undesirable effects. 

As far as I know, there are three potential ways to accomplish state-syncing in the current tab for this hook:

**Manually fire a storage event as you have done in this PR**

The approach you have taken in this PR is clever! My only (very small) concern with it is it changes expected browser behavior: it's possible a user does not expect this browser event to be fired in the same tab. I'm not sure what the potential consequence of changing this behavior is. Do you think this could cause issues?

**Explicitly add context and require users to use a provider**

This would make it most obvious to your average React user what's going on. Generally, context is a familiar concept. However, this is a big paradigm shift and users may not be too happy having to add a provider to their app.

**Use an external, reactive store along with [useSyncExternalStore](https://react.dev/reference/react/useSyncExternalStore)**

Avoids having to add context and also avoids changing browser behavior. However, I think this `useSyncExternalStore` hook is relatively new and may not support old React versions too well. Also, if not careful implementing an external store we could probably end up with memory leaks or other issues (I assume we'd want to use an external store library in this case).

---

Apologies for the brain-dump here, I just mostly want to make sure dispatching a Storage Event is the right direction and get your thoughts on the other options. Thanks!

**Comment by franciscop** [comment]
"Use an external, reactive store along with [useSyncExternalStore](https://react.dev/reference/react/useSyncExternalStore)" -> That's a narrow interpretation of "use an external store", which I would say should be the general way and using `useSyncExternalStore` is just an example implementation of it.

Basically all solutions are "use an store + an event system" (the source of truth + data sync between different parts), the nicest thing about @guoyunhe's solution is that it using `useState()` as the base store and the native browser events as the event system, no need to reinvent either.

I'll note the disadvantages of each approach:

- "Manually fire a storage event as you have done in this PR". What you noted basically, but I think it should be fine to fire the event even in the same window. I would have to think hard about the possibilities of an active conflict here with e.g. an extension.
- "Explicitly add context and require users to use a provider". We now need to add to the DX (Developer Experience) for the worse, and add a manual event system to sync the data up and down. IMHO since it's possible to solve the issue without worsening the DX, this is a no-go.
- "Use an external store with an event system". We'd have to implement both the external store system (or could use a fresh Redux's `createStore()`, but then we'd need to depend on Redux/similar) and the event system. Would work, but why go all the trouble?

There's a few other options, like I mentioned using an external store *library* like Redux, or also we could issue custom events like `selfstorage` instead of standard `storage` for the internal use-case. But I think overall chances of conflict with this library are so tiny that there's no need to worry. Heck, I'll go as far as to say I believe the spec is pretty bad in this case and it should trigger in the same window, maybe with a flag.

**Comment by nas5w** [comment]
Okay, I agree. I’m going to do a bit of additional testing and merge in to main shortly/do a release. Thanks guys!
